- name: Deploy Node.js app to EC2
  hosts: webservers
  become: yes

  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ServerAliveInterval=60'

  tasks:
    - name: Install required packages
      apt:
        name: ['git', 'curl']
        state: present
        update_cache: yes

    - name: Install Node.js
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
        apt-get install -y nodejs

    - name: Install PM2 globally
      npm:
        name: pm2
        global: yes

    - name: Create app directory
      file:
        path: /var/www/app
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Pull latest code from GitHub
      git:
        repo: https://github.com/ArjunLearning/ansible-ci-cd.git
        dest: /var/www/app
        version: main
        force: yes
        update: yes

    - name: Install dependencies
      shell: npm install
      args:
        chdir: /var/www/app

    - name: Start app with PM2
      shell: pm2 restart app || pm2 start src/app.js --name app
      args:
        chdir: /var/www/app
